const CATALOG_DEFS = {
  ai_recommended_movies: { name:"🤖 AI Recommended Movies", type:"movie", handler:"gemini_ai_recommended" },
  ai_recommended_series: { name:"🤖 AI Recommended Series", type:"series", handler:"gemini_ai_recommended" },
  rightnow_movies: { name: "✨ Right Now Movies", type: "movie", handler: "rightnow" },
  rightnow_series: { name: "✨ Right Now Series", type: "series", handler: "rightnow" },
  trending_movies:    { name:"Trending",        type:"movie",  handler:"tmdb_trending" },
  trending_series:    { name:"Trending",        type:"series", handler:"tmdb_trending" },
  popular_movies:     { name:"Popular",         type:"movie",  handler:"tmdb_source", source:"popular" },
  popular_series:     { name:"Popular",         type:"series", handler:"tmdb_source", source:"popular" },
  top_movies:         { name:"Top Rated",       type:"movie",  handler:"tmdb_source", source:"top_rated" },
  top_series:         { name:"Top Rated",       type:"series", handler:"tmdb_source", source:"top_rated" },
  now_movies:         { name:"Now Playing",            type:"movie",  handler:"tmdb_source", source:"now_playing" },
  airing_series:      { name:"Airing Today",           type:"series", handler:"tmdb_source", source:"airing_today" },
  ontheair_series:    { name:"On The Air",             type:"series", handler:"tmdb_source", source:"on_the_air" },
  anime_movies:       { name:"Anime",           type:"movie",  handler:"tmdb_anime" },
  anime_series:       { name:"Anime",           type:"series", handler:"tmdb_anime" },
  bollywood_movies:   { name:"Bollywood",       type:"movie",  handler:"tmdb_bollywood" },
  bollywood_series:   { name:"Bollywood",       type:"series", handler:"tmdb_bollywood" },
  paramount_movies:   { name:"Paramount",       type:"movie",  handler:"tmdb_paramount" },
  paramount_series:   { name:"Paramount",       type:"series", handler:"tmdb_paramount" },
  netflix_movies:     { name:"Netflix",         type:"movie",  handler:"tmdb_provider", provider: 8 },
  netflix_series:     { name:"Netflix",         type:"series", handler:"tmdb_provider", provider: 8 },
  amazon_movies:      { name:"Amazon",          type:"movie",  handler:"tmdb_provider", provider: 9 },
  amazon_series:      { name:"Amazon",          type:"series", handler:"tmdb_provider", provider: 9 },
  disney_movies:      { name:"Disney+",         type:"movie",  handler:"tmdb_provider", provider: 337 },
  disney_series:      { name:"Disney+",         type:"series", handler:"tmdb_provider", provider: 337 },
  hbo_movies:         { name:"HBO",             type:"movie",  handler:"tmdb_provider", provider: 1899 },
  hbo_series:         { name:"HBO",             type:"series", handler:"tmdb_provider", provider: 1899 },
  apple_movies:       { name:"Apple TV+",       type:"movie",  handler:"tmdb_provider", provider: 350 },
  apple_series:       { name:"Apple TV+",       type:"series", handler:"tmdb_provider", provider: 350 },
  peacock_movies:     { name:"Peacock",         type:"movie",  handler:"tmdb_provider", provider: 386 },
  peacock_series:     { name:"Peacock",         type:"series", handler:"tmdb_provider", provider: 386 },
  mgm_movies:         { name:"MGM+",            type:"movie",  handler:"tmdb_provider", provider: 268 },
  mgm_series:         { name:"MGM+",            type:"series", handler:"tmdb_network",  networkId: "6219|922" },
  starz_movies:       { name:"Starz",            type:"movie",  handler:"tmdb_provider", provider: 1855 },
  mubi_movies:        { name:"MUBI",             type:"movie",  handler:"tmdb_provider", provider: 11 },
  acorn_movies:       { name:"Acorn",           type:"movie",  handler:"tmdb_provider", provider: 87 },
  acorn_series:       { name:"Acorn",           type:"series", handler:"tmdb_provider", provider: 87 },
  shudder_movies:     { name:"Shudder",         type:"movie",  handler:"tmdb_provider", provider: 99 },
  shudder_series:     { name:"Shudder",         type:"series", handler:"tmdb_provider", provider: 99 },
  britbox_movies:     { name:"BritBox",         type:"movie",  handler:"tmdb_provider", provider: 151 },
  britbox_series:     { name:"BritBox",         type:"series", handler:"tmdb_provider", provider: 151 },
  itvx_movies:        { name:"ITVX",            type:"movie",  handler:"tmdb_provider", provider: 584 },
  itvx_series:        { name:"ITVX",            type:"series", handler:"tmdb_provider", provider: 584 },
  channel4_movies:    { name:"Channel 4",       type:"movie",  handler:"tmdb_provider", provider: 583 },
  channel4_series:    { name:"Channel 4",       type:"series", handler:"tmdb_provider", provider: 583 },
  crunchyroll_movies: { name:"Crunchyroll",     type:"movie",  handler:"tmdb_provider", provider: 283 },
  crunchyroll_series: { name:"Crunchyroll",     type:"series", handler:"tmdb_provider", provider: 283 },
  hidive_movies:      { name:"Hidive",          type:"movie",  handler:"tmdb_provider", provider: 430 },
  hidive_series:      { name:"Hidive",          type:"series", handler:"tmdb_provider", provider: 430 },
  hulu_movies:        { name:"Hulu",            type:"movie",  handler:"tmdb_provider", provider: 15 },
  hulu_series:        { name:"Hulu",            type:"series", handler:"tmdb_provider", provider: 15 },
  discovery_movies:   { name:"Discovery+",      type:"movie",  handler:"tmdb_provider", provider: 520 },
  discovery_series:   { name:"Discovery+",      type:"series", handler:"tmdb_provider", provider: 520 },
  natgeo_movies:      { name:"National Geographic", type:"movie",  handler:"tmdb_provider", provider: 1964 },
  natgeo_series:      { name:"National Geographic", type:"series", handler:"tmdb_provider", provider: 1964 },
  ae_series:          { name:"A&E",             type:"series", handler:"tmdb_provider", provider: 156 },
  animalplanet_series:{ name:"Animal Planet",   type:"series", handler:"tmdb_provider", provider: 399 },
  action_movies:      { name:"Action",          type:"movie",  handler:"tmdb_genre", genre: 28 },
  action_series:      { name:"Action",          type:"series", handler:"tmdb_genre", genre: 28 },
  comedy_movies:      { name:"Comedy",          type:"movie",  handler:"tmdb_genre", genre: 35 },
  comedy_series:      { name:"Comedy",          type:"series", handler:"tmdb_genre", genre: 35 },
  horror_movies:      { name:"Horror",          type:"movie",  handler:"tmdb_genre", genre: 27 },
  horror_series:      { name:"Horror",          type:"series", handler:"tmdb_genre", genre: 27 },
  scifi_movies:       { name:"Sci-Fi",          type:"movie",  handler:"tmdb_genre", genre: 878 },
  scifi_series:       { name:"Sci-Fi",          type:"series", handler:"tmdb_genre", genre: 878 },
  documentary_movies: { name:"Documentary",     type:"movie",  handler:"tmdb_genre", genre: 99 },
  documentary_series: { name:"Documentary",     type:"series", handler:"tmdb_genre", genre: 99 },
  romance_movies:     { name:"Romance",         type:"movie",  handler:"tmdb_genre", genre: 10749 },
  romance_series:     { name:"Romance",         type:"series", handler:"tmdb_genre", genre: 10749 },
  thriller_movies:    { name:"Thriller",        type:"movie",  handler:"tmdb_genre", genre: 53 },
  thriller_series:    { name:"Thriller",        type:"series", handler:"tmdb_genre", genre: 53 },
  crime_movies:       { name:"Crime",           type:"movie",  handler:"tmdb_genre", genre: 80 },
  crime_series:       { name:"Crime",           type:"series", handler:"tmdb_genre", genre: 80 },
  animation_movies:   { name:"Animated",        type:"movie",  handler:"tmdb_genre", genre: 16 },
  animation_series:   { name:"Animated",        type:"series", handler:"tmdb_genre", genre: 16 },
  family_movies:      { name:"Family",          type:"movie",  handler:"tmdb_genre", genre: 10751 },
  family_series:      { name:"Family",          type:"series", handler:"tmdb_genre", genre: 10751 },
  fantasy_movies:     { name:"Fantasy",         type:"movie",  handler:"tmdb_genre", genre: 14 },
  adventure_movies:   { name:"Adventure",        type:"movie",  handler:"tmdb_genre",    genre: 12 },
  adventure_series:   { name:"Adventure",        type:"series", handler:"tmdb_genre",    genre: 10759 },
  history_movies:     { name:"History",          type:"movie",  handler:"tmdb_genre",    genre: 36 },
  history_series:     { name:"History",          type:"series", handler:"tmdb_genre",    genre: 10767 },
  romcom_movies:      { name:"Rom-Com",          type:"movie",  handler:"tmdb_genre",    genre: 10749 },
  reality_series:     { name:"Reality TV",       type:"series", handler:"tmdb_genre",    genre: 10764 },
  war_movies:         { name:"War",              type:"movie",  handler:"tmdb_genre",    genre: 10752 },
  war_series:         { name:"War & Politics",   type:"series", handler:"tmdb_genre",    genre: 10768 },
  western_movies:     { name:"Western",          type:"movie",  handler:"tmdb_genre",    genre: 37 },
  curiosity_movies:   { name:"Curiosity",        type:"movie",  handler:"tmdb_genre",    genre: 99 },
  curiosity_series:   { name:"Curiosity",        type:"series", handler:"tmdb_genre",    genre: 10767 },
  new_movies:         { name:"New Releases",     type:"movie",  handler:"tmdb_genre",    genre: 28, sortBy:"primary_release_date.desc" },
  standup_movies:     { name:"Stand-up Comedy",  type:"movie",  handler:"mdb" },
  studio_mgm:         { name:"MGM",              type:"movie",  handler:"tmdb_company",  company: "21" },
  fantasy_series:     { name:"Fantasy",         type:"series", handler:"tmdb_genre", genre: 14 },
  mystery_movies:     { name:"Mystery",         type:"movie",  handler:"tmdb_genre", genre: 9648 },
  mystery_series:     { name:"Mystery",         type:"series", handler:"tmdb_genre", genre: 9648 },
  drama_movies:       { name:"Drama",           type:"movie",  handler:"tmdb_genre", genre: 18 },
  drama_series:       { name:"Drama",           type:"series", handler:"tmdb_genre", genre: 18 },
  theme_superhero:    { name:"Superhero",              type:"movie",  handler:"tmdb_keyword", keyword: 9715,  lang:"en" },
  theme_heist:        { name:"Heist",                  type:"movie",  handler:"tmdb_keyword", keyword: 10051, lang:"en" },
  theme_serialkiller: { name:"Serial Killer",          type:"movie",  handler:"tmdb_keyword", keyword: 10714, lang:"en" },
  theme_timeloop:     { name:"Time Loop",              type:"movie",  handler:"tmdb_keyword", keyword: 10854, lang:"en" },
  theme_mafia:      { name:"Mafia",      type:"movie", handler:"tmdb_keyword", keyword:10391, lang:"en" },
  theme_gangster:   { name:"Gangster",   type:"movie", handler:"tmdb_keyword", keyword:3149,  lang:"en" },
  theme_detective:  { name:"Detective",  type:"movie", handler:"tmdb_keyword", keyword:703,   lang:"en" },
  theme_police:     { name:"Police",     type:"movie", handler:"tmdb_keyword", keyword:6149,  lang:"en" },
  theme_prison:     { name:"Prison",     type:"movie", handler:"tmdb_keyword", keyword:378,   lang:"en" },
  theme_murder:     { name:"Murder Mystery", type:"movie", handler:"tmdb_keyword", keyword:9826, lang:"en" },
  theme_zombie:       { name:"Zombie",                 type:"movie",  handler:"tmdb_keyword", keyword: 12377, lang:"en" },
  theme_slasher:            { name:"Slasher",               type:"movie",  handler:"tmdb_keyword", keyword: 12339,  lang:"en" },
  theme_paranormal:         { name:"Paranormal",            type:"movie",  handler:"tmdb_keyword", keyword: 9853,   lang:"en" },
  theme_possession:         { name:"Possession",            type:"movie",  handler:"tmdb_keyword", keyword: 9712,   lang:"en" },
  theme_foundfootage:       { name:"Found Footage",         type:"movie",  handler:"tmdb_keyword", keyword: 163053, lang:"en" },
  theme_homeinvasion:       { name:"Home Invasion",         type:"movie",  handler:"tmdb_keyword", keyword: 14903,  lang:"en" },
  theme_creaturefeature:    { name:"Creature Feature",      type:"movie",  handler:"tmdb_keyword", keyword: 158126, lang:"en" },
  theme_psychological:      { name:"Psychological Horror",  type:"movie",  handler:"tmdb_keyword", keyword: 295907, lang:"en" },
  theme_horrorcomedy:       { name:"Horror Comedy",         type:"movie",  handler:"tmdb_keyword", keyword: 373400, lang:"en" },
  theme_folkhorror:         { name:"Folk Horror",           type:"movie",  handler:"tmdb_keyword", keyword: 209568, lang:"en" },
  theme_gothichorror:       { name:"Gothic Horror",         type:"movie",  handler:"tmdb_keyword", keyword: 15032,  lang:"en" },
  theme_bodyhorror:         { name:"Body Horror",           type:"movie",  handler:"tmdb_keyword", keyword: 283085, lang:"en" },
  theme_cosmichorror:       { name:"Cosmic Horror",         type:"movie",  handler:"tmdb_keyword", keyword: 215959, lang:"en" },
  theme_lovecraftian:       { name:"Lovecraftian Horror",   type:"movie",  handler:"tmdb_keyword", keyword: 287274, lang:"en" },
  theme_animalattack:       { name:"Animal Attack",         type:"movie",  handler:"tmdb_keyword", keyword: 5160,   lang:"en" },
  theme_werewolf:           { name:"Werewolf",              type:"movie",  handler:"tmdb_keyword", keyword: 12564,  lang:"en" },
  theme_vampire:            { name:"Vampire",               type:"movie",  handler:"tmdb_keyword", keyword: 3133,   lang:"en" },
  studio_marvel:      { name:"Marvel",                 type:"movie",  handler:"tmdb_company", company: 420 },
  studio_dc:          { name:"DC Films",               type:"movie",  handler:"tmdb_company", company: "429|128064|9993", excludeAnimation: true },
  studio_a24:         { name:"A24",                    type:"movie",  handler:"tmdb_company", company: 41077 },
  studio_blumhouse:   { name:"Blumhouse",              type:"movie",  handler:"tmdb_company", company: 3172 },
  studio_ghibli:      { name:"Studio Ghibli",          type:"movie",  handler:"tmdb_company", company: 10342 },
  studio_wb:          { name:"Warner Bros",              type:"movie",  handler:"tmdb_company", company: "174" },
  studio_universal:   { name:"Universal Pictures",        type:"movie",  handler:"tmdb_company", company: "33" },
  studio_sony:        { name:"Sony Pictures",             type:"movie",  handler:"tmdb_company", company: "34|5" },
  studio_disney:      { name:"Walt Disney Pictures",     type:"movie",  handler:"tmdb_company", company: "2" },
  studio_lucasfilm:   { name:"Lucasfilm",                type:"movie",  handler:"tmdb_company", company: "1" },
  studio_paramount:   { name:"Paramount Pictures",        type:"movie",  handler:"tmdb_company", company: "4" },
  studio_20thcentury: { name:"20th Century",              type:"movie",  handler:"tmdb_company", company: "25" },
  studio_lionsgate:   { name:"Lionsgate",                 type:"movie",  handler:"tmdb_company", company: "1632" },
  studio_newline:     { name:"New Line Cinema",           type:"movie",  handler:"tmdb_company", company: "12" },
  studio_canalplus:   { name:"Canal+",                    type:"movie",  handler:"tmdb_company", company: "104" },
  network_abc:        { name:"ABC",                       type:"series", handler:"tmdb_network", networkId: 2 },
  network_cbs:        { name:"CBS",                       type:"series", handler:"tmdb_network", networkId: 16 },
  network_fox:        { name:"FOX",                       type:"series", handler:"tmdb_network", networkId: 19 },
  network_nbc:        { name:"NBC",                       type:"series", handler:"tmdb_network", networkId: 6 },
  starz_series:       { name:"Starz",                     type:"series", handler:"tmdb_network", networkId: 318 },
  network_nickelodeon:{ name:"Nickelodeon",              type:"series", handler:"tmdb_network", networkId: 13 },
  network_nickjr:     { name:"Nick Jr",                  type:"series", handler:"tmdb_network", networkId: 35 },
  network_hbo:        { name:"HBO",                      type:"series", handler:"tmdb_network", networkId: 49 },
  network_showtime:   { name:"Showtime",                 type:"series", handler:"tmdb_network", networkId: 67 },
  network_fx:         { name:"FX",                       type:"series", handler:"tmdb_network", networkId: 88 },
  network_amc:        { name:"AMC",                      type:"series", handler:"tmdb_network", networkId: 174 },
  network_tnt:        { name:"TNT",                      type:"series", handler:"tmdb_network", networkId: 41 },
  network_usa:        { name:"USA Network",              type:"series", handler:"tmdb_network", networkId: 30 },
  network_syfy:       { name:"Syfy",                     type:"series", handler:"tmdb_network", networkId: 77 },
  network_tbs:        { name:"TBS",                      type:"series", handler:"tmdb_network", networkId: 32 },
  network_cc:         { name:"Comedy Central",           type:"series", handler:"tmdb_network", networkId: 47 },
  network_adultswim:  { name:"Adult Swim",               type:"series", handler:"tmdb_network", networkId: 80 },
  network_cartoon:    { name:"Cartoon Network",          type:"series", handler:"tmdb_network", networkId: 56 },
  network_mtv:        { name:"MTV",                      type:"series", handler:"tmdb_network", networkId: 33 },
  network_disney_ch:  { name:"Disney Channel",           type:"series", handler:"tmdb_network", networkId: 54 },
  network_history:    { name:"History",                  type:"series", handler:"tmdb_network", networkId: 65 },
  network_discovery:  { name:"Discovery",                type:"series", handler:"tmdb_network", networkId: 64 },
  network_bravo:      { name:"Bravo",                    type:"series", handler:"tmdb_network", networkId: 74 },
  network_tlc:        { name:"TLC",                      type:"series", handler:"tmdb_network", networkId: 270 },
  network_aande:      { name:"A&E",                      type:"series", handler:"tmdb_network", networkId: 129 },
  network_hgtv:       { name:"HGTV",                     type:"series", handler:"tmdb_network", networkId: 294 },
  network_bbc:        { name:"BBC One",                  type:"series", handler:"tmdb_network", networkId: 4 },
  network_ch4:        { name:"Channel 4",                type:"series", handler:"tmdb_network", networkId: 9 },
  network_cw:         { name:"The CW",                   type:"series", handler:"tmdb_network", networkId: 71 },
  network_pbs:        { name:"PBS",                      type:"series", handler:"tmdb_network", networkId: 14 },
  decade_2020s:       { name:"2020s Movies",             type:"movie",  handler:"mdb", source:"mdb_91304" },
  decade_2010s:       { name:"2010s Movies",             type:"movie",  handler:"mdb", source:"mdb_91303" },
  decade_2000s:       { name:"2000s Movies",             type:"movie",  handler:"mdb", source:"mdb_91302" },
  decade_1990s:       { name:"1990s Movies",             type:"movie",  handler:"mdb", source:"mdb_91300" },
  decade_1980s:       { name:"1980s Movies",             type:"movie",  handler:"mdb", source:"mdb_91301" },
  decade_1970s:       { name:"1970s Movies",             type:"movie",  handler:"tmdb_genre", yearFrom:1970, yearTo:1979 },
  decade_1960s:       { name:"1960s Movies",             type:"movie",  handler:"tmdb_genre", yearFrom:1960, yearTo:1969 },
  decade_1950s:       { name:"1950s Movies",             type:"movie",  handler:"tmdb_genre", yearFrom:1950, yearTo:1959 },

  quietplace_coll:    { name:"A Quiet Place",           type:"movie", handler:"tmdb_collection", collectionId: 521226 },
  aceventura_coll:    { name:"Ace Ventura",             type:"movie", handler:"tmdb_collection", collectionId: 3167 },
  alvin_coll:         { name:"Alvin and the Chipmunks", type:"movie", handler:"tmdb_collection", collectionId: 167613 },
  americanpie_coll:   { name:"American Pie",            type:"movie", handler:"tmdb_collection", collectionId: 2806 },
  anchorman_coll:     { name:"Anchorman",               type:"movie", handler:"tmdb_collection", collectionId: 93791 },
  austinpowers_coll:  { name:"Austin Powers",           type:"movie", handler:"tmdb_collection", collectionId: 1006 },
  badboys_coll:       { name:"Bad Boys",                type:"movie", handler:"tmdb_collection", collectionId: 14890 },
  behindenemy_coll:   { name:"Behind Enemy Lines",      type:"movie", handler:"tmdb_collection", collectionId: 98513 },
  beverlyhills_coll:  { name:"Beverly Hills Cop",       type:"movie", handler:"tmdb_collection", collectionId: 85861 },
  blade_coll:         { name:"Blade",                   type:"movie", handler:"tmdb_collection", collectionId: 735 },
  bladerunner_coll:   { name:"Blade Runner",            type:"movie", handler:"tmdb_collection", collectionId: 422837 },
  bridgetjones_coll:  { name:"Bridget Jones",           type:"movie", handler:"tmdb_collection", collectionId: 8936 },
  bringiton_coll:     { name:"Bring It On",             type:"movie", handler:"tmdb_collection", collectionId: 430186 },
  cars_coll:          { name:"Cars",                    type:"movie", handler:"tmdb_collection", collectionId: 87118 },
  childsplay_coll:    { name:"Child's Play",            type:"movie", handler:"tmdb_collection", collectionId: 10455 },
  clerks_coll:        { name:"Clerks",                  type:"movie", handler:"tmdb_collection", collectionId: 182813 },
  creed_coll:         { name:"Creed",                   type:"movie", handler:"tmdb_collection", collectionId: 553717 },
  daddyshome_coll:    { name:"Daddy's Home",            type:"movie", handler:"tmdb_collection", collectionId: 473971 },
  demonslayer_coll:   { name:"Demon Slayer",            type:"movie", handler:"tmdb_collection", collectionId: 925155 },
  wimpykid_coll:      { name:"Diary of a Wimpy Kid",    type:"movie", handler:"tmdb_collection", collectionId: 86110 },
  dirtyharry_coll:    { name:"Dirty Harry",             type:"movie", handler:"tmdb_collection", collectionId: 10456 },
  divergent_coll:     { name:"Divergent",               type:"movie", handler:"tmdb_collection", collectionId: 283579 },
  dontbreathe_coll:   { name:"Don't Breathe",           type:"movie", handler:"tmdb_collection", collectionId: 748919 },
  dragonball_coll:    { name:"Dragon Ball",             type:"movie", handler:"tmdb_collection", collectionId: 386410 },
  enolaholmes_coll:   { name:"Enola Holmes",            type:"movie", handler:"tmdb_collection", collectionId: 829314 },
  escaperoom_coll:    { name:"Escape Room",             type:"movie", handler:"tmdb_collection", collectionId: 769423 },
  evangelion_coll:    { name:"Evangelion",              type:"movie", handler:"tmdb_collection", collectionId: 210303 },
  manofsteel_coll:    { name:"Man of Steel",   type:"movie", handler:"tmdb_collection", collectionId: 233248 },
  residentevil_coll:  { name:"Resident Evil",  type:"movie", handler:"tmdb_collection", collectionId: 17255 },
  criterion_movies:   { name:"Criterion Collection", type:"movie", handler:"tmdb_company", company: 204170 },
  evildead_coll:      { name:"Evil Dead",               type:"movie", handler:"tmdb_collection", collectionId: 1960 },
  fantasticbeasts_coll: { name:"Fantastic Beasts",      type:"movie", handler:"tmdb_collection", collectionId: 435259 },
  fiftyshades_coll:   { name:"Fifty Shades",            type:"movie", handler:"tmdb_collection", collectionId: 344830 },
  finaldestination_coll: { name:"Final Destination",    type:"movie", handler:"tmdb_collection", collectionId: 8864 },
  friday13_coll:      { name:"Friday the 13th",         type:"movie", handler:"tmdb_collection", collectionId: 1190758 },
  ghostbusters_coll:  { name:"Ghostbusters",            type:"movie", handler:"tmdb_collection", collectionId: 2980 },
  godzilla_coll:      { name:"Godzilla",                type:"movie", handler:"tmdb_collection", collectionId: 535313 },
  hannibal_coll:      { name:"Hannibal Lecter",         type:"movie", handler:"tmdb_collection", collectionId: 9743 },
  hellraiser_coll:    { name:"Hellraiser",              type:"movie", handler:"tmdb_collection", collectionId: 8917 },
  homealone_coll:     { name:"Home Alone",              type:"movie", handler:"tmdb_collection", collectionId: 9888 },
  hoteltransylvania_coll: { name:"Hotel Transylvania",  type:"movie", handler:"tmdb_collection", collectionId: 185103 },
  insidious_coll:     { name:"Insidious",               type:"movie", handler:"tmdb_collection", collectionId: 228446 },
  it_coll:            { name:"It",                      type:"movie", handler:"tmdb_collection", collectionId: 477962 },
  jarhead_coll:       { name:"Jarhead",                 type:"movie", handler:"tmdb_collection", collectionId: 285564 },
  jaws_coll:          { name:"Jaws",                    type:"movie", handler:"tmdb_collection", collectionId: 2366 },
  jumanji_coll:       { name:"Jumanji",                 type:"movie", handler:"tmdb_collection", collectionId: 495527 },
  jumpstreet_coll:    { name:"Jump Street",             type:"movie", handler:"tmdb_collection", collectionId: 212562 },
  kingkong_coll:      { name:"King Kong",               type:"movie", handler:"tmdb_collection", collectionId: 135498 },
  legallyblonde_coll: { name:"Legally Blonde",          type:"movie", handler:"tmdb_collection", collectionId: 86024 },
  lethalweapon_coll:  { name:"Lethal Weapon",           type:"movie", handler:"tmdb_collection", collectionId: 945 },
  madagascar_coll:    { name:"Madagascar",              type:"movie", handler:"tmdb_collection", collectionId: 14740 },
  magicmike_coll:     { name:"Magic Mike",              type:"movie", handler:"tmdb_collection", collectionId: 328247 },
  majorleague_coll:   { name:"Major League",            type:"movie", handler:"tmdb_collection", collectionId: 97771 },
  meetparents_coll:   { name:"Meet the Parents",        type:"movie", handler:"tmdb_collection", collectionId: 51509 },
  meninblack_coll:    { name:"Men in Black",            type:"movie", handler:"tmdb_collection", collectionId: 86119 },
  missinginaction_coll: { name:"Missing in Action",     type:"movie", handler:"tmdb_collection", collectionId: 46512 },
  monsters_coll:      { name:"Monsters Inc",            type:"movie", handler:"tmdb_collection", collectionId: 137696 },
  myheroacademia_coll: { name:"My Hero Academia",       type:"movie", handler:"tmdb_collection", collectionId: 1189668 },
  naruto_coll:        { name:"Naruto",                  type:"movie", handler:"tmdb_collection", collectionId: 23616 },
  lampoon_coll:       { name:"National Lampoon",        type:"movie", handler:"tmdb_collection", collectionId: 1362787 },
  nationaltreasure_coll: { name:"National Treasure",    type:"movie", handler:"tmdb_collection", collectionId: 52984 },
  nightmuseum_coll:   { name:"Night at the Museum",     type:"movie", handler:"tmdb_collection", collectionId: 1369645 },
  nowyouseeme_coll:   { name:"Now You See Me",          type:"movie", handler:"tmdb_collection", collectionId: 382685 },
  onepiece_coll:      { name:"One Piece",               type:"movie", handler:"tmdb_collection", collectionId: 23456 },
  pacificrim_coll:    { name:"Pacific Rim",             type:"movie", handler:"tmdb_collection", collectionId: 363369 },
  paddington_coll:    { name:"Paddington",              type:"movie", handler:"tmdb_collection", collectionId: 488924 },
  paranormal_coll:    { name:"Paranormal Activity",     type:"movie", handler:"tmdb_collection", collectionId: 41437 },
  percyjackson_coll:  { name:"Percy Jackson",           type:"movie", handler:"tmdb_collection", collectionId: 179919 },
  pitchperfect_coll:  { name:"Pitch Perfect",           type:"movie", handler:"tmdb_collection", collectionId: 306031 },
  poltergeist_coll:   { name:"Poltergeist",             type:"movie", handler:"tmdb_collection", collectionId: 10453 },
  purge_coll:         { name:"The Purge",               type:"movie", handler:"tmdb_collection", collectionId: 256322 },
  ring_coll:          { name:"The Ring",                type:"movie", handler:"tmdb_collection", collectionId: 14563 },
  secretlifepets_coll: { name:"Secret Life of Pets",    type:"movie", handler:"tmdb_collection", collectionId: 427084 },
  transporter_coll:   { name:"The Transporter",         type:"movie", handler:"tmdb_collection", collectionId: 9518 },
  twilight_coll:      { name:"Twilight",                type:"movie", handler:"tmdb_collection", collectionId: 1193510 },
  topgun_coll:        { name:"Top Gun",                 type:"movie", handler:"tmdb_collection", collectionId: 531330 },
  tremors_coll:       { name:"Tremors",                 type:"movie", handler:"tmdb_collection", collectionId: 91799 },
  trolls_coll:        { name:"Trolls",                  type:"movie", handler:"tmdb_collection", collectionId: 1184152 },
  tron_coll:          { name:"TRON",                    type:"movie", handler:"tmdb_collection", collectionId: 63043 },
  underworld_coll:    { name:"Underworld",              type:"movie", handler:"tmdb_collection", collectionId: 2326 },
  waynesworld_coll:   { name:"Wayne's World",           type:"movie", handler:"tmdb_collection", collectionId: 8979 },
  wreckitralph_coll:  { name:"Wreck-It Ralph",          type:"movie", handler:"tmdb_collection", collectionId: 404825 },
  zoolander_coll:     { name:"Zoolander",               type:"movie", handler:"tmdb_collection", collectionId: 352789 },
  sicario_coll:       { name:"Sicario",                 type:"movie", handler:"tmdb_collection", collectionId: 496796 },
  sing_coll:          { name:"Sing",                    type:"movie", handler:"tmdb_collection", collectionId: 544670 },
  sniper_coll:        { name:"Sniper",                  type:"movie", handler:"tmdb_collection", collectionId: 14246 },
  stepup_coll:        { name:"Step Up",                 type:"movie", handler:"tmdb_collection", collectionId: 86092 },
  addamsfamily_coll:  { name:"The Addams Family",       type:"movie", handler:"tmdb_collection", collectionId: 11716 },
  boondocksaints_coll: { name:"Boondock Saints",        type:"movie", handler:"tmdb_collection", collectionId: 87186 },
  bossbaby_coll:      { name:"The Boss Baby",           type:"movie", handler:"tmdb_collection", collectionId: 519457 },
  narnia_coll:        { name:"Chronicles of Narnia",    type:"movie", handler:"tmdb_collection", collectionId: 925022 },
  darkknight_coll:    { name:"The Dark Knight",         type:"movie", handler:"tmdb_collection", collectionId: 263 },
  dirtydozen_coll:    { name:"The Dirty Dozen",         type:"movie", handler:"tmdb_collection", collectionId: 124492 },
  equalizer_coll:     { name:"The Equalizer",           type:"movie", handler:"tmdb_collection", collectionId: 523855 },
  exorcist_coll:      { name:"The Exorcist",            type:"movie", handler:"tmdb_collection", collectionId: 1283238 },
  grudge_coll:        { name:"The Grudge",              type:"movie", handler:"tmdb_collection", collectionId: 1974 },
  hangover_coll:      { name:"The Hangover",            type:"movie", handler:"tmdb_collection", collectionId: 86119 },
  karatekid_coll:     { name:"The Karate Kid",          type:"movie", handler:"tmdb_collection", collectionId: 8580 },
  lego_coll:          { name:"The Lego Movie",          type:"movie", handler:"tmdb_collection", collectionId: 325470 },
  mightyducks_coll:   { name:"The Mighty Ducks",        type:"movie", handler:"tmdb_collection", collectionId: 10709 },
  mummy_coll:         { name:"The Mummy",               type:"movie", handler:"tmdb_collection", collectionId: 1733 },
  omen_coll:          { name:"The Omen",                type:"movie", handler:"tmdb_collection", collectionId: 10919 },
  robocop_coll:       { name:"RoboCop",                 type:"movie", handler:"tmdb_collection", collectionId: 5547 },
  rocky_coll:         { name:"Rocky",                   type:"movie", handler:"tmdb_collection", collectionId: 1575 },
  rushhour_coll:      { name:"Rush Hour",               type:"movie", handler:"tmdb_collection", collectionId: 90863 },
  scoobydoo_coll:     { name:"Scooby-Doo",              type:"movie", handler:"tmdb_collection", collectionId: 86860 },
  langdon_coll:       { name:"Robert Langdon",          type:"movie", handler:"tmdb_collection", collectionId: 86121 },
  starshiptroopers_coll: { name:"Starship Troopers",    type:"movie", handler:"tmdb_collection", collectionId: 10522 },
  vhs_coll:           { name:"V/H/S",                   type:"movie", handler:"tmdb_collection", collectionId: 207621 },
  xxx_coll:           { name:"xXx",                     type:"movie", handler:"tmdb_collection", collectionId: 1590319 },
  goal_coll:          { name:"Goal!",                   type:"movie", handler:"tmdb_collection", collectionId: 110177 },
  bigmomma_coll:      { name:"Big Momma's House",       type:"movie", handler:"tmdb_collection", collectionId: 44979 },
  pokemon_coll:       { name:"Pokémon",                 type:"movie", handler:"tmdb_collection", collectionId: 34055 },
  detectiveconan_coll: { name:"Detective Conan",        type:"movie", handler:"tmdb_collection", collectionId: 39199 },
  startrek_coll:      { name:"Star Trek",                 type:"movie",  handler:"tmdb_multi_collection", collectionIds: [151, 115570, 115575] },
  director_nolan:     { name:"Christopher Nolan",      type:"movie",  handler:"tmdb_director", personId: 525 },
  director_scorsese:  { name:"Martin Scorsese",         type:"movie",  handler:"tmdb_director", personId: 1032 },
  director_spielberg: { name:"Steven Spielberg",        type:"movie",  handler:"tmdb_director", personId: 488 },
  director_villeneuve:{ name:"Denis Villeneuve",        type:"movie",  handler:"tmdb_director", personId: 137427 },
  director_fincher:   { name:"David Fincher",           type:"movie",  handler:"tmdb_director", personId: 7467 },
  director_kubrick:   { name:"Stanley Kubrick",         type:"movie",  handler:"tmdb_director", personId: 240 },
  director_hitchcock: { name:"Alfred Hitchcock",        type:"movie",  handler:"tmdb_director", personId: 2636 },
  director_wes:       { name:"Wes Anderson",    type:"movie", handler:"tmdb_director", personId: 5655 },
  director_anderson:  { name:"Wes Anderson",            type:"movie",  handler:"tmdb_director", personId: 5655 },
  director_burton:    { name:"Tim Burton",              type:"movie",  handler:"tmdb_director", personId: 510 },
  director_tarantino: { name:"Quentin Tarantino",       type:"movie",  handler:"tmdb_director", personId: 138 },
  director_hughes:    { name:"John Hughes",              type:"movie",  handler:"tmdb_director", personId: 11505 },
  actor_sandler:         { name:"Adam Sandler",               type:"movie",  handler:"tmdb_actor", personId: 19292 },
  actor_jolie:         { name:"Angelina Jolie",               type:"movie",  handler:"tmdb_actor", personId: 11701 },
  actor_pitt:         { name:"Brad Pitt",               type:"movie",  handler:"tmdb_actor", personId: 287 },
  actor_bale:         { name:"Christian Bale",               type:"movie",  handler:"tmdb_actor", personId: 3894 },
  actor_eastwood:         { name:"Clint Eastwood",               type:"movie",  handler:"tmdb_actor", personId: 190 },
  actor_denzel:         { name:"Denzel Washington",               type:"movie",  handler:"tmdb_actor", personId: 5292 },
  actor_carrey:         { name:"Jim Carrey",               type:"movie",  handler:"tmdb_actor", personId: 206 },
  actor_depp:         { name:"Johnny Depp",               type:"movie",  handler:"tmdb_actor", personId: 85 },
  actor_dicaprio:         { name:"Leonardo DiCaprio",               type:"movie",  handler:"tmdb_actor", personId: 6193 },
  actor_robbie:         { name:"Margot Robbie",               type:"movie",  handler:"tmdb_actor", personId: 234352 },
  actor_damon:         { name:"Matt Damon",               type:"movie",  handler:"tmdb_actor", personId: 1892 },
  actor_freeman:         { name:"Morgan Freeman",               type:"movie",  handler:"tmdb_actor", personId: 192 },
  actor_deniro:         { name:"Robert De Niro",               type:"movie",  handler:"tmdb_actor", personId: 380 },
  actor_rdj:         { name:"Robert Downey Jr",               type:"movie",  handler:"tmdb_actor", personId: 3223 },
  actor_gosling:         { name:"Ryan Gosling",               type:"movie",  handler:"tmdb_actor", personId: 30614 },
  actor_reynolds:         { name:"Ryan Reynolds",               type:"movie",  handler:"tmdb_actor", personId: 10859 },
  actor_rogen:         { name:"Seth Rogen",               type:"movie",  handler:"tmdb_actor", personId: 19274 },
  actor_cruise:         { name:"Tom Cruise",               type:"movie",  handler:"tmdb_actor", personId: 500 },
  actor_hanks:         { name:"Tom Hanks",               type:"movie",  handler:"tmdb_actor", personId: 31 },
  actor_ferrell:         { name:"Will Ferrell",               type:"movie",  handler:"tmdb_actor", personId: 23659 },
  actor_smith:         { name:"Will Smith",               type:"movie",  handler:"tmdb_actor", personId: 2888 },
  actor_schwarzenegger: { name:"Arnold Schwarzenegger", type:"movie", handler:"tmdb_actor", personId: 1100 },
  actor_stiller:      { name:"Ben Stiller",           type:"movie", handler:"tmdb_actor", personId: 7399 },
  actor_cumberbatch:  { name:"Benedict Cumberbatch",  type:"movie", handler:"tmdb_actor", personId: 71580 },
  actor_murray:       { name:"Bill Murray",            type:"movie", handler:"tmdb_actor", personId: 1532 },
  actor_tatum:        { name:"Channing Tatum",         type:"movie", handler:"tmdb_actor", personId: 38673 },
  actor_norris:       { name:"Chuck Norris",           type:"movie", handler:"tmdb_actor", personId: 51576 },
  actor_craig:        { name:"Daniel Craig",           type:"movie", handler:"tmdb_actor", personId: 8784 },
  actor_johnson:      { name:"Dwayne Johnson",         type:"movie", handler:"tmdb_actor", personId: 18918 },
  actor_stone:        { name:"Emma Stone",             type:"movie", handler:"tmdb_actor", personId: 54693 },
  actor_pugh:         { name:"Florence Pugh",          type:"movie", handler:"tmdb_actor", personId: 1373737 },
  actor_clooney:      { name:"George Clooney",         type:"movie", handler:"tmdb_actor", personId: 1461 },
  actor_ford:         { name:"Harrison Ford",          type:"movie", handler:"tmdb_actor", personId: 3 },
  actor_black:        { name:"Jack Black",             type:"movie", handler:"tmdb_actor", personId: 70851 },
  actor_chan:         { name:"Jackie Chan",             type:"movie", handler:"tmdb_actor", personId: 18897 },
  actor_gyllenhaal:   { name:"Jake Gyllenhaal",        type:"movie", handler:"tmdb_actor", personId: 131 },
  actor_statham:      { name:"Jason Statham",          type:"movie", handler:"tmdb_actor", personId: 976 },
  actor_ortega:       { name:"Jenna Ortega",           type:"movie", handler:"tmdb_actor", personId: 974169 },
  actor_aniston:      { name:"Jennifer Aniston",       type:"movie", handler:"tmdb_actor", personId: 4491 },
  actor_lawrence:     { name:"Jennifer Lawrence",      type:"movie", handler:"tmdb_actor", personId: 72129 },
  actor_hill:         { name:"Jonah Hill",             type:"movie", handler:"tmdb_actor", personId: 21007 },
  actor_roberts:      { name:"Julia Roberts",          type:"movie", handler:"tmdb_actor", personId: 1204 },
  actor_heigl:        { name:"Katherine Heigl",        type:"movie", handler:"tmdb_actor", personId: 25541 },
  actor_collins:      { name:"Lily Collins",           type:"movie", handler:"tmdb_actor", personId: 79007 },
  actor_mcconaughey:  { name:"Matthew McConaughey",    type:"movie", handler:"tmdb_actor", personId: 10297 },
  actor_mccarthy:     { name:"Melissa McCarthy",       type:"movie", handler:"tmdb_actor", personId: 55536 },
  actor_streep:       { name:"Meryl Streep",           type:"movie", handler:"tmdb_actor", personId: 5064 },
  actor_herbig:       { name:"Michael Herbig",         type:"movie", handler:"tmdb_actor", personId: 18072 },
  actor_kunis:        { name:"Mila Kunis",             type:"movie", handler:"tmdb_actor", personId: 18973 },
  actor_brown:        { name:"Millie Bobby Brown",     type:"movie", handler:"tmdb_actor", personId: 1356210 },
  actor_cage:         { name:"Nicolas Cage",           type:"movie", handler:"tmdb_actor", personId: 2963 },
  actor_kidman:       { name:"Nicole Kidman",          type:"movie", handler:"tmdb_actor", personId: 2227 },
  actor_wilson:       { name:"Owen Wilson",            type:"movie", handler:"tmdb_actor", personId: 887 },
  actor_witherspoon:  { name:"Reese Witherspoon",      type:"movie", handler:"tmdb_actor", personId: 368 },
  actor_williams:     { name:"Robin Williams",         type:"movie", handler:"tmdb_actor", personId: 2157 },
  actor_wayne:        { name:"John Wayne",             type:"movie", handler:"tmdb_actor", personId: 4165 },
  actor_jackson:      { name:"Samuel L. Jackson",      type:"movie", handler:"tmdb_actor", personId: 2231 },
  actor_bullock:      { name:"Sandra Bullock",         type:"movie", handler:"tmdb_actor", personId: 879 },
  actor_carell:       { name:"Steve Carell",           type:"movie", handler:"tmdb_actor", personId: 4495 },
  actor_sweeney:      { name:"Sydney Sweeney",         type:"movie", handler:"tmdb_actor", personId: 115440 },
  actor_stallone:     { name:"Sylvester Stallone",     type:"movie", handler:"tmdb_actor", personId: 1024 },
  actor_chalamet:     { name:"Timothee Chalamet",      type:"movie", handler:"tmdb_actor", personId: 1190668 },
  actor_holland:      { name:"Tom Holland",            type:"movie", handler:"tmdb_actor", personId: 1243774 },
  actor_hathaway:     { name:"Anne Hathaway",   type:"movie", handler:"tmdb_actor", personId: 1813 },
  actor_zendaya:      { name:"Zendaya",                type:"movie", handler:"tmdb_actor", personId: 505710 },
  director_depalma:   { name:"Brian De Palma",         type:"movie", handler:"tmdb_director", personId: 1150 },
  director_lynch:     { name:"David Lynch",            type:"movie", handler:"tmdb_director", personId: 5602 },
  director_coppola:   { name:"Francis Ford Coppola",   type:"movie", handler:"tmdb_director", personId: 1776 },
  director_gerwig:    { name:"Greta Gerwig",           type:"movie", handler:"tmdb_director", personId: 45400 },
  director_deltoro:   { name:"Guillermo del Toro",     type:"movie", handler:"tmdb_director", personId: 10828 },
  director_cameron:   { name:"James Cameron",          type:"movie", handler:"tmdb_director", personId: 2710 },
  director_carpenter: { name:"John Carpenter",         type:"movie", handler:"tmdb_director", personId: 10397 },
  director_pta:       { name:"Paul Thomas Anderson",   type:"movie", handler:"tmdb_director", personId: 59 },
  director_jackson:   { name:"Peter Jackson",          type:"movie", handler:"tmdb_director", personId: 108 },
  director_scott:     { name:"Ridley Scott",           type:"movie", handler:"tmdb_director", personId: 578 },
  director_lee:       { name:"Spike Lee",              type:"movie", handler:"tmdb_director", personId: 5281 },

  hp_collection:      { name:"Harry Potter",          type:"movie",  handler:"tmdb_collection", collectionId: 1241 },
  lotr_collection:    { name:"Lord of the Rings",       type:"movie",  handler:"tmdb_collection", collectionId: 119 },
  starwars_collection:{ name:"Star Wars",               type:"movie",  handler:"tmdb_collection", collectionId: 10 },
  bond_collection:    { name:"James Bond",              type:"movie",  handler:"tmdb_collection", collectionId: 645 },
  fastfurious_coll:   { name:"Fast & Furious",         type:"movie",  handler:"tmdb_collection", collectionId: 9485 },
  johnwick_coll:      { name:"John Wick",               type:"movie",  handler:"tmdb_collection", collectionId: 404609 },
  mi_collection:      { name:"Mission Impossible",      type:"movie",  handler:"tmdb_collection", collectionId: 87359 },
  indiana_collection: { name:"Indiana Jones",           type:"movie",  handler:"tmdb_collection", collectionId: 84 },
  jurassic_coll:      { name:"Jurassic Park",           type:"movie",  handler:"tmdb_collection", collectionId: 328 },
  hobbit_collection:  { name:"The Hobbit",              type:"movie",  handler:"tmdb_collection", collectionId: 121938 },
  avengers_coll:      { name:"The Avengers",            type:"movie",  handler:"tmdb_collection", collectionId: 86311 },
  mcu_collection: {
    name:"MCU Infinity Saga · Release Order",
    type:"movie",
    handler:"tmdb_ids",
    ids: [
      1726,1724,10138,10195,1771,24428,68721,76338,
      100402,118340,99861,102899,271110,284052,283995,
      315635,284053,284054,299536,363088,299537,299534,
      429617
    ]
  },

  mcu_chronological: {
    name:"MCU Infinity Saga · Chronological Order",
    type:"movie",
    handler:"tmdb_ids",
    ids: [
      1771,299537,1726,10138,1724,10195,24428,76338,
      68721,100402,118340,283995,99861,102899,271110,
      284054,315635,284052,284053,363088,299536,299534,
      429617
    ]
  },
  xmen_collection:    { name:"X-Men",                   type:"movie",  handler:"tmdb_collection", collectionId: 748 },
  hungergames_coll:   { name:"Hunger Games",            type:"movie",  handler:"tmdb_collection", collectionId: 131635 },
  pirates_collection: { name:"Pirates of Caribbean",   type:"movie",  handler:"tmdb_collection", collectionId: 295 },
  shrek_collection:   { name:"Shrek",                  type:"movie",  handler:"tmdb_collection", collectionId: 2150 },
  iceage_collection:  { name:"Ice Age",                type:"movie",  handler:"tmdb_collection", collectionId: 8354 },
  httyd_collection:   { name:"How To Train Your Dragon",type:"movie",  handler:"tmdb_collection", collectionId: 89137 },
  madmax_collection:  { name:"Mad Max",                type:"movie",  handler:"tmdb_collection", collectionId: 8945 },
  bourne_collection:  { name:"The Bourne",             type:"movie",  handler:"tmdb_collection", collectionId: 31562 },
  oceans_collection:  { name:"Ocean's",              type:"movie",  handler:"tmdb_collection", collectionId: 304 },
  transformers_coll:  { name:"Transformers",           type:"movie",  handler:"tmdb_collection", collectionId: 8650 },
  captainamerica_coll:{ name:"Captain America",        type:"movie",  handler:"tmdb_collection", collectionId: 131295 },
  ironman_collection: { name:"Iron Man",               type:"movie",  handler:"tmdb_collection", collectionId: 131292 },
  gotg_collection:    { name:"Guardians of the Galaxy",type:"movie",  handler:"tmdb_collection", collectionId: 284433 },
  doctorstrange_coll: { name:"Doctor Strange",         type:"movie",  handler:"tmdb_collection", collectionId: 618529 },
  blackpanther_coll:  { name:"Black Panther",          type:"movie",  handler:"tmdb_collection", collectionId: 529892 },
  antman_collection:  { name:"Ant-Man",                type:"movie",  handler:"tmdb_collection", collectionId: 422834 },
  wonderwoman_coll:   { name:"Wonder Woman",           type:"movie",  handler:"tmdb_collection", collectionId: 468552 },
  aquaman_collection: { name:"Aquaman",                type:"movie",  handler:"tmdb_collection", collectionId: 573693 },
  planetapes_coll:    { name:"Planet of the Apes",     type:"movie",  handler:"tmdb_collection", collectionId: 1709 },
  kingsman_coll:      { name:"Kingsman",               type:"movie",  handler:"tmdb_collection", collectionId: 391860 },
  taken_collection:   { name:"Taken",                 type:"movie",  handler:"tmdb_collection", collectionId: 135483 },
  alien_collection:   { name:"Alien",                 type:"movie",  handler:"tmdb_collection", collectionId: 8091 },
  terminator_coll:    { name:"Terminator",            type:"movie",  handler:"tmdb_collection", collectionId: 528 },
  predator_coll:      { name:"Predator",              type:"movie",  handler:"tmdb_collection", collectionId: 399 },
  thor_collection:    { name:"Thor",                  type:"movie",  handler:"tmdb_collection", collectionId: 131296 },
  halloween_coll:     { name:"Halloween",             type:"movie",  handler:"tmdb_collection", collectionId: 91361 },
  nightmare_coll:     { name:"Nightmare on Elm Street",type:"movie", handler:"tmdb_collection", collectionId: 8581 },
  saw_collection:     { name:"Saw",                   type:"movie",  handler:"tmdb_collection", collectionId: 656 },
  scream_collection:  { name:"Scream",                type:"movie",  handler:"tmdb_collection", collectionId: 2602 },
  conjuring_coll:     { name:"The Conjuring",         type:"movie",  handler:"tmdb_collection", collectionId: 313086 },
  despicableme_coll:  { name:"Despicable Me",         type:"movie",  handler:"tmdb_collection", collectionId: 86066 },
  kungfupanda_coll:   { name:"Kung Fu Panda",         type:"movie",  handler:"tmdb_collection", collectionId: 77816 },
  incredibles_coll:   { name:"The Incredibles",       type:"movie",  handler:"tmdb_collection", collectionId: 468222 },
  deadpool_coll:      { name:"Deadpool",              type:"movie",  handler:"tmdb_collection", collectionId: 448150 },
  sherlock_coll:      { name:"Sherlock Holmes",       type:"movie",  handler:"tmdb_collection", collectionId: 102322 },
  findingnemo_coll:   { name:"Finding Nemo",          type:"movie",  handler:"tmdb_collection", collectionId: 137697 },
  toystory_coll:      { name:"Toy Story",             type:"movie",  handler:"tmdb_collection", collectionId: 10194 },
  backtofuture_coll:  { name:"Back to the Future",    type:"movie",  handler:"tmdb_collection", collectionId: 264 },
  matrix_collection:  { name:"The Matrix",            type:"movie",  handler:"tmdb_collection", collectionId: 2344 },
  diehard_collection: { name:"Die Hard",              type:"movie",  handler:"tmdb_collection", collectionId: 1570 },
  rambo_collection:   { name:"Rambo",                 type:"movie",  handler:"tmdb_collection", collectionId: 5039 },
  expendables_coll:   { name:"The Expendables",       type:"movie",  handler:"tmdb_collection", collectionId: 126125 },
  shrek2_collection:  { name:"Minions",               type:"movie",  handler:"tmdb_collection", collectionId: 544669 },
  dune_collection:    { name:"Dune",                   type:"movie",  handler:"tmdb_collection", collectionId: 726871 },
  godfather_collection:{ name:"The Godfather",         type:"movie",  handler:"tmdb_collection", collectionId: 230 },
  spiderman_collection:{ name:"Spider-Man",              type:"movie",  handler:"tmdb_multi_collection", collectionIds: [556, 531241, 573436] },
  avatar_collection:  { name:"Avatar",                   type:"movie",  handler:"tmdb_collection", collectionId: 87096 },
  scarymovie_coll:    { name:"Scary Movie",              type:"movie",  handler:"tmdb_collection", collectionId: 4246 },
  knivesout_coll:     { name:"Knives Out",               type:"movie",  handler:"tmdb_collection", collectionId: 722971 },
  mazerunner_coll:    { name:"Maze Runner",              type:"movie",  handler:"tmdb_collection", collectionId: 295130 },
  superman_collection:{ name:"Superman",               type:"movie",  handler:"tmdb_multi_collection", collectionIds: [8537, 209131, 1540907, 593251] },
  batman_collection:  { name:"Batman",                type:"movie",  handler:"tmdb_multi_collection", collectionIds: [120794, 263, 948485] },
  mdb_trakt_trending_movies:  { name:"Trakt Trending",          type:"movie",  handler:"mdb", listId:"87667" },
  mdb_trakt_trending_series:  { name:"Trakt Trending",          type:"series", handler:"mdb", listId:"88434" },
  simkl_watchlist_movies:   { name:"My Simkl Watchlist",   type:"movie",  handler:"simkl_watchlist" },
  simkl_watchlist_series:   { name:"My Simkl Watchlist",   type:"series", handler:"simkl_watchlist" },
  simkl_completed_movies:   { name:"My Simkl Completed",   type:"movie",  handler:"simkl_completed" },
  simkl_completed_series:   { name:"My Simkl Completed",   type:"series", handler:"simkl_completed" },
  simkl_watching_series:    { name:"My Simkl Watching",    type:"series", handler:"simkl_watching" },
  simkl_rated_movies:       { name:"My Simkl Ratings",     type:"movie",  handler:"simkl_rated" },
  simkl_rated_series:       { name:"My Simkl Ratings",     type:"series", handler:"simkl_rated" },
  trakt_trending_movies:   { name:"Trakt Trending",    type:"movie",  handler:"trakt_trending" },
  trakt_trending_series:   { name:"Trakt Trending",    type:"series", handler:"trakt_trending" },
  trakt_popular_movies:    { name:"Trakt Popular",     type:"movie",  handler:"trakt_popular" },
  trakt_popular_series:    { name:"Trakt Popular",     type:"series", handler:"trakt_popular" },
  trakt_anticipated_movies:{ name:"Trakt Anticipated", type:"movie",  handler:"trakt_anticipated" },
  trakt_anticipated_series:{ name:"Trakt Anticipated", type:"series", handler:"trakt_anticipated" },
  trakt_fav_movies:        { name:"My Trakt Favorites",type:"movie",  handler:"trakt_user_favorites" },
  trakt_fav_series:        { name:"My Trakt Favorites",type:"series", handler:"trakt_user_favorites" },
  trakt_watchlist_movies:  { name:"My Trakt Watchlist",type:"movie",  handler:"trakt_user_watchlist" },
  trakt_watchlist_series:  { name:"My Trakt Watchlist",type:"series", handler:"trakt_user_watchlist" },
  trakt_collection_movies: { name:"My Trakt Collection",type:"movie", handler:"trakt_user_collection" },
  trakt_collection_series: { name:"My Trakt Collection",type:"series",handler:"trakt_user_collection" },
  mdb_top_movies_week:   { name:"Top Movies This Week",           type:"movie",  handler:"mdb", listId:"2236" },
  mdb_most_popular_movies:   { name:"Most Popular (Top 20)",          type:"movie",  handler:"mdb", listId:"1198" },
  mdb_imdb_moviemeter_top100:     { name:"IMDb Moviemeter Top 100",        type:"movie",  handler:"mdb", listId:"69" },
  mdb_latest_digital_release:  { name:"Latest Digital Release",         type:"movie",  handler:"mdb", listId:"86934" },
  mdb_latest_releases:    { name:"Latest Releases",                type:"movie",  handler:"mdb", listId:"960" },
  mdb_latest_bluray_releases:   { name:"Latest Blu-ray Releases",        type:"movie",  handler:"mdb", listId:"2202" },
  mdb_latest_certified_fresh:   { name:"Latest Certified Fresh",         type:"movie",  handler:"mdb", listId:"1176" },
  mdb_latest_airing_shows:  { name:"Latest Airing Shows",            type:"series", handler:"mdb", listId:"86710" },
  mdb_trending_kids_movies:  { name:"Trending Kids",           type:"movie",  handler:"mdb", listId:"88307" },
  mdb_trending_kids_series:  { name:"Trending Kids",           type:"series", handler:"mdb", listId:"88309" },
  mdb_top_kids_movies_week:     { name:"Top Kids Movies This Week",      type:"movie",  handler:"mdb", listId:"13" },
  mdb_netflix_latest_movies:  { name:"Netflix Latest Movies",          type:"movie",  handler:"mdb", listId:"88328" },
  mdb_netflix_latest_series:  { name:"Netflix Latest Series",          type:"series", handler:"mdb", listId:"86751" },
  mdb_amazon_latest_movies:  { name:"Amazon Latest Movies",           type:"movie",  handler:"mdb", listId:"86755" },
  mdb_amazon_latest_series:  { name:"Amazon Latest Series",           type:"series", handler:"mdb", listId:"86753" },
  mdb_appletv_latest_movies:  { name:"Apple TV Plus Latest Movies",    type:"movie",  handler:"mdb", listId:"88317" },
  mdb_appletv_latest_series:  { name:"Apple TV Plus Latest Series",    type:"series", handler:"mdb", listId:"88319" },
  mdb_disney_latest_movies:  { name:"Disney Plus Latest Movies",      type:"movie",  handler:"mdb", listId:"86759" },
  mdb_disney_latest_series:  { name:"Disney Plus Latest Series",      type:"series", handler:"mdb", listId:"86758" },
  mdb_hbo_latest_movies:  { name:"HBO Latest Movies",              type:"movie",  handler:"mdb", listId:"89647" },
  mdb_hbo_latest_series:  { name:"HBO Latest Series",              type:"series", handler:"mdb", listId:"89649" },
  mdb_paramount_latest_movies:  { name:"Paramount Plus Latest Movies",   type:"movie",  handler:"mdb", listId:"86762" },
  mdb_paramount_latest_series:  { name:"Paramount Plus Latest Series",   type:"series", handler:"mdb", listId:"86761" },
  mdb_hulu_latest_movies:  { name:"Hulu Latest Movies",             type:"movie",  handler:"mdb", listId:"88326" },
  mdb_hulu_latest_series:  { name:"Hulu Latest Series",             type:"series", handler:"mdb", listId:"88327" },
  mdb_top_documentaries_movies:  { name:"Top Documentaries",              type:"movie",  handler:"mdb", listId:"84677" },
  mdb_documentary_series:  { name:"Documentary",         type:"series", handler:"mdb", listId:"84403" },
  mdb_history_war_movies:   { name:"History & War",                type:"movie",  handler:"mdb", listId:"8043" },
  mdb_nature_series:  { name:"Nature",                     type:"series", handler:"mdb", listId:"84487" },
  mdb_reality_tv_series:  { name:"Reality TV",                 type:"series", handler:"mdb", listId:"84401" },
  mdb_standup_comedy_movies:  { name:"Standup Comedy",             type:"movie",  handler:"mdb", listId:"83497" },
  mdb_mindfuck_movies:   { name:"Must-See Mindfuck",              type:"movie",  handler:"mdb", listId:"3892" },
  mdb_plot_twists_movies:   { name:"Crazy Plot Twists",              type:"movie",  handler:"mdb", listId:"3923" },
  mdb_outer_space_movies:   { name:"Outer Space",                    type:"movie",  handler:"mdb", listId:"3920" },
  mdb_time_travel_movies:   { name:"Time Travel",                    type:"movie",  handler:"mdb", listId:"2909" },
  mdb_modern_horror_movies: { name:"Must-See Modern Horror",         type:"movie",  handler:"mdb", listId:"102554" },
  mdb_horror_classics_movies:   { name:"Horror Classics",                type:"movie",  handler:"mdb", listId:"2410" },
  mdb_rotten_tomatoes_100_movies:   { name:"100pct Rotten Tomatoes",         type:"movie",  handler:"mdb", listId:"3885" },
  mdb_parody_movies:   { name:"Top 50 Parody Movies",           type:"movie",  handler:"mdb", listId:"4081" },
  mdb_true_crime_movies:   { name:"True Crime Documentaries",       type:"movie",  handler:"mdb", listId:"4390" },
  mdb_thrilling_movies:   { name:"Thrilling Movies",               type:"movie",  handler:"mdb", listId:"2858" },
  mdb_seasonal_movies: { name:"Seasonal",                       type:"movie",  handler:"mdb", listId:"136620" },
  mdb_pixar_movies:   { name:"Pixar Collection",               type:"movie",  handler:"mdb", listId:"3918" },
  mdb_dreamworks_movies:   { name:"DreamWorks Collection",          type:"movie",  handler:"mdb", listId:"3928" },
  mdb_bbc_shows_series:   { name:"BBC Shows",                      type:"series", handler:"mdb", listId:"3087" },
  mdb_uk_shows_series:   { name:"UK Shows",                       type:"series", handler:"mdb", listId:"3091" },
  mdb_best_of_2025:  { name:"Best of 2025",                   type:"movie",  handler:"mdb", listId:"92337" },
  mdb_best_of_2020s:  { name:"Best of 2020s",                  type:"movie",  handler:"mdb", listId:"91304" },
  mdb_best_of_2010s:  { name:"Best of 2010s",                  type:"movie",  handler:"mdb", listId:"91303" },
  mdb_best_of_2000s:  { name:"Best of 2000s",                  type:"movie",  handler:"mdb", listId:"91302" },
  mdb_best_of_1990s:  { name:"Best of 1990s",                  type:"movie",  handler:"mdb", listId:"91300" },
  mdb_best_of_1980s:  { name:"Best of 1980s",                  type:"movie",  handler:"mdb", listId:"91301" },
  search_movie: { name:"Ultra MAX", type:"movie",  handler:"search" },
  search_movies: { name:"Ultra MAX", type:"movie",  handler:"search" },
  search_series: { name:"Ultra MAX", type:"series", handler:"search" },

    // TV Collections / Universes
    got_tv_collection: { name:"Game of Thrones Universe", type:"series", handler:"tmdb_ids", ids:[1399, 94997] },
    sopranos_tv_collection:     { name:"The Sopranos",             type:"series", handler:"tmdb_search", query:"The Sopranos" },
    outlander_tv_collection:    { name:"Outlander",                type:"series", handler:"tmdb_search", query:"Outlander" },
    theboys_tv_collection: { name:"The Boys Universe", type:"series", handler:"tmdb_ids", ids:[76479, 205715] },
    breakingbad_tv_collection:  { name:"Breaking Bad Universe",    type:"series", handler:"tmdb_ids", ids:[1396, 60059] },
    yellowstone_tv_collection: { name:"Yellowstone Universe", type:"series", handler:"tmdb_ids", ids:[73586, 118357, 157744] },
    walkingdead_tv_collection: { name:"Walking Dead Universe", type:"series", handler:"tmdb_ids", ids:[1402, 62286, 211684, 194583, 206586] },
    dexter_tv_collection: { name:"Dexter Universe", type:"series", handler:"tmdb_ids", ids:[1405, 131927, 219937, 259909] },
    power_tv_collection: { name:"Power Universe", type:"series", handler:"tmdb_ids", ids:[54650, 97890, 124394, 119845] },

  // ── MERGED CATALOGUE ROWS ──────────────────────────────────────────
  // handler:"merged" combines results from several other CATALOG_DEFS
  // entries into one deduplicated, re-sorted row. See "merged" case in
  // catalog-handler-service.js for the fetch/dedupe/sort implementation.
  merged_streaming_movies: {
    name: "🎬 All Streaming Movies", type: "movie", handler: "merged",
    sources: ["netflix_movies","amazon_movies","disney_movies","hbo_movies","apple_movies","peacock_movies","hulu_movies","paramount_movies"]
  },
  merged_streaming_series: {
    name: "📺 All Streaming Series", type: "series", handler: "merged",
    sources: ["netflix_series","amazon_series","disney_series","hbo_series","apple_series","peacock_series","hulu_series","paramount_series"]
  },
  merged_staff_picks_movies: {
    name: "⭐ Staff Picks", type: "movie", handler: "merged",
    sources: ["trending_movies","top_movies"]
  },
  merged_staff_picks_series: {
    name: "⭐ Staff Picks Series", type: "series", handler: "merged",
    sources: ["trending_series","top_series"]
  },
  merged_new_this_week_movies: {
    name: "🆕 New This Week", type: "movie", handler: "merged",
    sources: ["netflix_movies","amazon_movies","disney_movies","hbo_movies","apple_movies","peacock_movies"],
    sortField: "release_date"
  },
  merged_new_this_week_series: {
    name: "🆕 New Episodes This Week", type: "series", handler: "merged",
    sources: ["netflix_series","amazon_series","disney_series","hbo_series","apple_series","peacock_series"],
    sortField: "release_date"
  },
  merged_hidden_gems_movies: {
    name: "💎 Hidden Gems", type: "movie", handler: "merged",
    sources: ["action_movies","drama_movies","comedy_movies","thriller_movies","scifi_movies","horror_movies"],
    minVoteAverage: 7, minVoteCount: 50, maxVoteCount: 1500, sortField: "vote_average"
  },
  merged_hidden_gems_series: {
    name: "💎 Hidden Gems Series", type: "series", handler: "merged",
    sources: ["drama_series","comedy_series","thriller_series","scifi_series","crime_series"],
    minVoteAverage: 7, minVoteCount: 50, maxVoteCount: 1500, sortField: "vote_average"
  },
  // ─────────────────────────────────────────────────────────────────

  // ── MyAnimeList (MAL) personal catalogs ────────────────────────────
  mal_watching:    { name: "📺 MAL Watching",           type: "series", handler: "mal_watching" },
  mal_plantowatch: { name: "📋 MAL Plan to Watch",       type: "series", handler: "mal_plantowatch" },
  mal_completed:   { name: "✅ MAL Recently Completed",  type: "series", handler: "mal_completed" },
  // ─────────────────────────────────────────────────────────────────

  // ── AniList personal + discovery catalogs ──────────────────────────
  anilist_watching:    { name: "🎬 AniList Watching",      type: "series", handler: "anilist_watching" },
  anilist_plantowatch: { name: "📋 AniList Plan to Watch",  type: "series", handler: "anilist_plantowatch" },
  anilist_trending:    { name: "🔥 AniList Trending",       type: "series", handler: "anilist_trending" },
  anilist_seasonal:    { name: "🌸 AniList This Season",    type: "series", handler: "anilist_seasonal" },
  // ─────────────────────────────────────────────────────────────────

};

// Legacy catalog ids — before these MDBList-backed rows had readable slugs,
// their id was just "mdb_" + the raw MDBList numeric list id (e.g.
// "mdb_88328"). Nuvio's "Follow Home Layout" mode titles a row from its raw
// id rather than its manifest name for ids like that, so users saw rows
// labelled "Mdb_88328 - Movie" instead of "Netflix Latest". CATALOG_DEFS
// keys were renamed to human-readable slugs (the MDBList list id now lives
// in each def's `listId` field for the actual API call) — this map lets
// already-installed users' saved `catalogs`/`catalogOrder`/`hiddenCatalogs`
// selections (and any client still requesting the old id directly) keep
// resolving to the same catalog.
const MDB_ID_ALIASES = {
  mdb_87667: "mdb_trakt_trending_movies",
  mdb_88434: "mdb_trakt_trending_series",
  mdb_2236: "mdb_top_movies_week",
  mdb_1198: "mdb_most_popular_movies",
  mdb_69: "mdb_imdb_moviemeter_top100",
  mdb_86934: "mdb_latest_digital_release",
  mdb_960: "mdb_latest_releases",
  mdb_2202: "mdb_latest_bluray_releases",
  mdb_1176: "mdb_latest_certified_fresh",
  mdb_86710: "mdb_latest_airing_shows",
  mdb_88307: "mdb_trending_kids_movies",
  mdb_88309: "mdb_trending_kids_series",
  mdb_13: "mdb_top_kids_movies_week",
  mdb_88328: "mdb_netflix_latest_movies",
  mdb_86751: "mdb_netflix_latest_series",
  mdb_86755: "mdb_amazon_latest_movies",
  mdb_86753: "mdb_amazon_latest_series",
  mdb_88317: "mdb_appletv_latest_movies",
  mdb_88319: "mdb_appletv_latest_series",
  mdb_86759: "mdb_disney_latest_movies",
  mdb_86758: "mdb_disney_latest_series",
  mdb_89647: "mdb_hbo_latest_movies",
  mdb_89649: "mdb_hbo_latest_series",
  mdb_86762: "mdb_paramount_latest_movies",
  mdb_86761: "mdb_paramount_latest_series",
  mdb_88326: "mdb_hulu_latest_movies",
  mdb_88327: "mdb_hulu_latest_series",
  mdb_84677: "mdb_top_documentaries_movies",
  mdb_84403: "mdb_documentary_series",
  mdb_8043: "mdb_history_war_movies",
  mdb_84487: "mdb_nature_series",
  mdb_84401: "mdb_reality_tv_series",
  mdb_83497: "mdb_standup_comedy_movies",
  mdb_3892: "mdb_mindfuck_movies",
  mdb_3923: "mdb_plot_twists_movies",
  mdb_3920: "mdb_outer_space_movies",
  mdb_2909: "mdb_time_travel_movies",
  mdb_102554: "mdb_modern_horror_movies",
  mdb_2410: "mdb_horror_classics_movies",
  mdb_3885: "mdb_rotten_tomatoes_100_movies",
  mdb_4081: "mdb_parody_movies",
  mdb_4390: "mdb_true_crime_movies",
  mdb_2858: "mdb_thrilling_movies",
  mdb_136620: "mdb_seasonal_movies",
  mdb_3918: "mdb_pixar_movies",
  mdb_3928: "mdb_dreamworks_movies",
  mdb_3087: "mdb_bbc_shows_series",
  mdb_3091: "mdb_uk_shows_series",
  mdb_92337: "mdb_best_of_2025",
  mdb_91304: "mdb_best_of_2020s",
  mdb_91303: "mdb_best_of_2010s",
  mdb_91302: "mdb_best_of_2000s",
  mdb_91300: "mdb_best_of_1990s",
  mdb_91301: "mdb_best_of_1980s",
};

function resolveCatalogId(id) {
  return MDB_ID_ALIASES[id] || id;
}

module.exports = {
  CATALOG_DEFS,
  MDB_ID_ALIASES,
  resolveCatalogId
};
